[project]
name = "hello-robot-stretch4-kinematics"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hello-robot-stretch4-urdf>=2026.5.27",
    "numpy>=2.2.6",
    "pin>=4.0.0",
    "yourdfpy>=0.0.60",
]

[project.optional-dependencies]
demos = [
    "hello-robot-stretch4-body>=2026.8.21",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["stretch4_kinematics*"]
